-- ============================================================
-- ICT 운영관리 - 마스터 테이블
-- Oracle 12c 이상 IDENTITY 컬럼 사용
-- ============================================================

-- 담당자 마스터 (Staff)
CREATE TABLE "STAFF_MASTER" (
    "STAFF_ID"      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 담당자 ID
    "NAME"          VARCHAR2(100) NOT NULL,                 -- 담당자명
    "EMPLOYEE_NO"   VARCHAR2(20),                           -- 사번
    "DEPARTMENT"    VARCHAR2(100),                         -- 부서
    "DEPT_CODE"     VARCHAR2(20),                           -- 부서코드
    "RESPONS"       VARCHAR2(200),                          -- 담당업무
    "EMAIL"         VARCHAR2(255),                         -- 이메일
    "TEL"           VARCHAR2(50),                          -- 연락처
    "MPHONE"        VARCHAR2(50),                           -- 휴대전화번호
    "STATUS"        VARCHAR2(20) DEFAULT 'ACTIVE',           -- 상태 (ACTIVE/INACTIVE 등)
    "DESC"   VARCHAR2(2000),                         -- 설명
    "CREATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP,         -- 등록일시
    "UPDATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP          -- 수정일시
);

COMMENT ON TABLE "STAFF_MASTER" IS '담당자 마스터';
COMMENT ON COLUMN "STAFF_MASTER"."DESC" IS '설명';
COMMENT ON COLUMN "STAFF_MASTER"."STATUS" IS '사용유무 (Y/N)';
COMMENT ON COLUMN "STAFF_MASTER"."STAFF_ID" IS '담당자 ID';
COMMENT ON COLUMN "STAFF_MASTER"."NAME" IS '담당자명';
COMMENT ON COLUMN "STAFF_MASTER"."EMPLOYEE_NO" IS '사번';
COMMENT ON COLUMN "STAFF_MASTER"."DEPARTMENT" IS '부서';
COMMENT ON COLUMN "STAFF_MASTER"."DEPT_CODE" IS '부서코드';
COMMENT ON COLUMN "STAFF_MASTER"."RESPONS" IS '담당업무';
COMMENT ON COLUMN "STAFF_MASTER"."EMAIL" IS '이메일';
COMMENT ON COLUMN "STAFF_MASTER"."TEL" IS '연락처';
COMMENT ON COLUMN "STAFF_MASTER"."MPHONE" IS '휴대전화번호';


-- 서버 마스터 (Server)
CREATE TABLE "SERVER_MASTER" (
    "SERVER_ID"     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 서버 ID
    "SERVER_NAME"   VARCHAR2(200) NOT NULL,                 -- 서버명
    "HOSTNAME"      VARCHAR2(255),                         -- 호스트명
    "IP_ADDRESS"    VARCHAR2(45),                          -- IP 주소
    "OS_TYPE"       VARCHAR2(100),                         -- OS 유형
    "OS_VERSION"    VARCHAR2(100),                          -- OS 버전
    "CPU_CORES"     NUMBER(10),                             -- CPU 코어 수
    "CPU_MODEL"     VARCHAR2(200),                         -- CPU 모델명
    "MEMORY_GB"     NUMBER(10,2),                           -- 메모리(GB)
    "LOCATION"      VARCHAR2(200),                          -- 물리적 위치
    "STATUS"        VARCHAR2(20) DEFAULT 'ACTIVE',          -- 상태 (ACTIVE/INACTIVE 등)
    "SYS_STAGE"     VARCHAR2(20),                          -- 시스템 단계 (DEV/STG/PRD 등)
    "NW_ZONE"       VARCHAR2(100),                         -- 네트워크 존
    "VIP"           VARCHAR2(255),                         -- VIP
    "LB"            VARCHAR2(255),                         -- LB (로드밸런서)
    "STAFF_1_ID"    NUMBER(10) REFERENCES "STAFF_MASTER"("STAFF_ID"),   -- 담당 스태프 1
    "STAFF_2_ID"    NUMBER(10) REFERENCES "STAFF_MASTER"("STAFF_ID"),   -- 담당 스태프 2
    "STAFF_3_ID"    NUMBER(10) REFERENCES "STAFF_MASTER"("STAFF_ID"),   -- 담당 스태프 3
    "STAFF_4_ID"    NUMBER(10) REFERENCES "STAFF_MASTER"("STAFF_ID"),   -- 담당 스태프 4
    "DESC"   VARCHAR2(2000),                         -- 설명
    "CREATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP,         -- 등록일시
    "UPDATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP          -- 수정일시
);

COMMENT ON TABLE "SERVER_MASTER" IS '서버 마스터';
COMMENT ON COLUMN "SERVER_MASTER"."SERVER_ID" IS '서버 ID';
COMMENT ON COLUMN "SERVER_MASTER"."SERVER_NAME" IS '서버명';
COMMENT ON COLUMN "SERVER_MASTER"."HOSTNAME" IS '호스트명';
COMMENT ON COLUMN "SERVER_MASTER"."IP_ADDRESS" IS 'IP 주소';
COMMENT ON COLUMN "SERVER_MASTER"."OS_TYPE" IS 'OS 유형';
COMMENT ON COLUMN "SERVER_MASTER"."OS_VERSION" IS 'OS 버전';
COMMENT ON COLUMN "SERVER_MASTER"."CPU_CORES" IS 'CPU 코어 수';
COMMENT ON COLUMN "SERVER_MASTER"."CPU_MODEL" IS 'CPU 모델명';
COMMENT ON COLUMN "SERVER_MASTER"."MEMORY_GB" IS '메모리(GB)';
COMMENT ON COLUMN "SERVER_MASTER"."LOCATION" IS '물리적 위치';
COMMENT ON COLUMN "SERVER_MASTER"."DESC" IS '설명';
COMMENT ON COLUMN "SERVER_MASTER"."STATUS" IS '상태 (ACTIVE/INACTIVE 등)';
COMMENT ON COLUMN "SERVER_MASTER"."SYS_STAGE" IS '시스템 단계 (DEV/STG/PRD 등)';
COMMENT ON COLUMN "SERVER_MASTER"."NW_ZONE" IS '네트워크 존';
COMMENT ON COLUMN "SERVER_MASTER"."VIP" IS 'VIP';
COMMENT ON COLUMN "SERVER_MASTER"."LB" IS 'LB (로드밸런서)';
COMMENT ON COLUMN "SERVER_MASTER"."STAFF_1_ID" IS '담당 스태프 1';
COMMENT ON COLUMN "SERVER_MASTER"."STAFF_2_ID" IS '담당 스태프 2';
COMMENT ON COLUMN "SERVER_MASTER"."STAFF_3_ID" IS '담당 스태프 3';
COMMENT ON COLUMN "SERVER_MASTER"."STAFF_4_ID" IS '담당 스태프 4';


-- 솔루션 마스터 (Solution) - 벤더 정보 병합
CREATE TABLE "SOLU_MASTER" (
    "SOLU_ID"   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 솔루션 ID
    "SOLU_NAME" VARCHAR2(200) NOT NULL,                 -- 솔루션명
    "VERSION"       VARCHAR2(50),                          -- 버전
    "PRG_LANG"      VARCHAR2(100),                         -- 개발언어 (Programming Language)
    "JAVA_YN"       CHAR(1),                               -- Java 사용 여부 (Y/N)
    "SOLU_TYPE" VARCHAR2(100),                         -- 솔루션 유형
    "DESC"   VARCHAR2(2000),                        -- 설명
    "VENDOR_NAME"   VARCHAR2(200),                         -- 벤더명 (병합)
    "CONTACT_NAME"  VARCHAR2(100),                         -- 벤더 담당자명
    "CONTACT_PHONE" VARCHAR2(50),                          -- 벤더 연락처
    "CONTACT_EMAIL" VARCHAR2(255),                         -- 벤더 이메일
    "ADDRESS"       VARCHAR2(500),                         -- 벤더 주소
    "SALES_REP_NAME"  VARCHAR2(100),                        -- 영업대표 (1인)
    "SALES_REP_PHONE" VARCHAR2(50),                         -- 영업대표 전화번호
    "SALES_REP_EMAIL" VARCHAR2(255),                        -- 영업대표 이메일
    "SUPPORT_1_NAME"  VARCHAR2(100),                        -- 담당자 1
    "SUPPORT_1_PHONE" VARCHAR2(50),                        -- 담당자 1 전화번호
    "SUPPORT_1_EMAIL" VARCHAR2(255),                        -- 담당자 1 이메일
    "SUPPORT_2_NAME"  VARCHAR2(100),                        -- 담당자 2
    "SUPPORT_2_PHONE" VARCHAR2(50),                        -- 담당자 2 전화번호
    "SUPPORT_2_EMAIL" VARCHAR2(255),                        -- 담당자 2 이메일
    "VENDOR_DESC" CLOB,                              -- 벤더 설명
    "STATUS"        VARCHAR2(20) DEFAULT 'ACTIVE',         -- 상태 (ACTIVE/INACTIVE 등)
    "STAFF_1_ID"    NUMBER(10) REFERENCES "STAFF_MASTER"("STAFF_ID"),   -- 담당 스태프 1
    "STAFF_2_ID"    NUMBER(10) REFERENCES "STAFF_MASTER"("STAFF_ID"),   -- 담당 스태프 2
    "STAFF_3_ID"    NUMBER(10) REFERENCES "STAFF_MASTER"("STAFF_ID"),   -- 담당 스태프 3
    "STAFF_4_ID"    NUMBER(10) REFERENCES "STAFF_MASTER"("STAFF_ID"),   -- 담당 스태프 4
    "CREATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP,         -- 등록일시
    "UPDATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP         -- 수정일시
);

COMMENT ON TABLE "SOLU_MASTER" IS '솔루션 마스터 (벤더 정보 병합)';
COMMENT ON COLUMN "SOLU_MASTER"."SOLU_ID" IS '솔루션 ID';
COMMENT ON COLUMN "SOLU_MASTER"."SOLU_NAME" IS '솔루션명';
COMMENT ON COLUMN "SOLU_MASTER"."VERSION" IS '버전';
COMMENT ON COLUMN "SOLU_MASTER"."PRG_LANG" IS '개발언어 (Programming Language)';
COMMENT ON COLUMN "SOLU_MASTER"."JAVA_YN" IS 'Java 사용 여부 (Y/N)';
COMMENT ON COLUMN "SOLU_MASTER"."SOLU_TYPE" IS '솔루션 유형';
COMMENT ON COLUMN "SOLU_MASTER"."DESC" IS '설명';
COMMENT ON COLUMN "SOLU_MASTER"."VENDOR_NAME" IS '벤더명';
COMMENT ON COLUMN "SOLU_MASTER"."CONTACT_NAME" IS '벤더 담당자명';
COMMENT ON COLUMN "SOLU_MASTER"."CONTACT_PHONE" IS '벤더 연락처';
COMMENT ON COLUMN "SOLU_MASTER"."CONTACT_EMAIL" IS '벤더 이메일';
COMMENT ON COLUMN "SOLU_MASTER"."ADDRESS" IS '벤더 주소';
COMMENT ON COLUMN "SOLU_MASTER"."SALES_REP_NAME" IS '영업대표 (1인)';
COMMENT ON COLUMN "SOLU_MASTER"."SALES_REP_PHONE" IS '영업대표 전화번호';
COMMENT ON COLUMN "SOLU_MASTER"."SALES_REP_EMAIL" IS '영업대표 이메일';
COMMENT ON COLUMN "SOLU_MASTER"."SUPPORT_1_NAME" IS '담당자 1';
COMMENT ON COLUMN "SOLU_MASTER"."SUPPORT_1_PHONE" IS '담당자 1 전화번호';
COMMENT ON COLUMN "SOLU_MASTER"."SUPPORT_1_EMAIL" IS '담당자 1 이메일';
COMMENT ON COLUMN "SOLU_MASTER"."SUPPORT_2_NAME" IS '담당자 2';
COMMENT ON COLUMN "SOLU_MASTER"."SUPPORT_2_PHONE" IS '담당자 2 전화번호';
COMMENT ON COLUMN "SOLU_MASTER"."SUPPORT_2_EMAIL" IS '담당자 2 이메일';
COMMENT ON COLUMN "SOLU_MASTER"."VENDOR_DESC" IS '벤더 설명';
COMMENT ON COLUMN "SOLU_MASTER"."STATUS" IS '상태 (ACTIVE/INACTIVE 등)';
COMMENT ON COLUMN "SOLU_MASTER"."STAFF_1_ID" IS '담당 스태프 1';
COMMENT ON COLUMN "SOLU_MASTER"."STAFF_2_ID" IS '담당 스태프 2';
COMMENT ON COLUMN "SOLU_MASTER"."STAFF_3_ID" IS '담당 스태프 3';
COMMENT ON COLUMN "SOLU_MASTER"."STAFF_4_ID" IS '담당 스태프 4';


-- 서비스 마스터 (Service)
CREATE TABLE "SERVICE_MASTER" (
    "SERVICE_ID"     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 서비스 ID
    "SERVICE_NAME"  VARCHAR2(200) NOT NULL,                 -- 서비스명
    "SERVICE_ACCOUNT" VARCHAR2(100),                         -- 서비스계정
    "PWD"           VARCHAR2(200),                          -- 비밀번호
    "PWD_EXPIRE_DT" DATE,                                    -- 비번만료일
    "DESC"          VARCHAR2(2000),                          -- 설명
    "CREATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP,         -- 등록일시
    "UPDATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP         -- 수정일시
);

COMMENT ON TABLE "SERVICE_MASTER" IS '서비스 마스터';
COMMENT ON COLUMN "SERVICE_MASTER"."SERVICE_ID" IS '서비스 ID';
COMMENT ON COLUMN "SERVICE_MASTER"."SERVICE_NAME" IS '서비스명';
COMMENT ON COLUMN "SERVICE_MASTER"."SERVICE_ACCOUNT" IS '서비스계정';
COMMENT ON COLUMN "SERVICE_MASTER"."PWD" IS '비밀번호';
COMMENT ON COLUMN "SERVICE_MASTER"."PWD_EXPIRE_DT" IS '비번만료일';
COMMENT ON COLUMN "SERVICE_MASTER"."DESC" IS '설명';
