-- ============================================================
-- ICT 운영관리 - 마스터 테이블
-- Oracle 12c 이상 IDENTITY 컬럼 사용
-- ============================================================

-- 스태프 마스터 (Staff)
CREATE TABLE "MST_STAFF" (
    "STAFF_ID"      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 스태프 ID
    "NAME"          VARCHAR2(100) NOT NULL,                 -- 스태프명
    "EMPLOYEE_NO"   VARCHAR2(20),                           -- 사번
    "DEPARTMENT"    VARCHAR2(100),                         -- 부서
    "DEPT_CODE"     VARCHAR2(20),                           -- 부서코드
    "RESPONS"       VARCHAR2(200),                          -- 담당업무
    "EMAIL"         VARCHAR2(255),                         -- 이메일
    "TEL"           VARCHAR2(50),                          -- 연락처
    "MPHONE"        VARCHAR2(50),                           -- 휴대전화번호
    "STATUS"        VARCHAR2(20) DEFAULT 'ACTIVE',           -- 상태 (ACTIVE/INACTIVE 등)
    "DESC"   VARCHAR2(2000),                         -- 설명
    "CREATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP,         -- 등록일시
    "UPDATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP          -- 수정일시
);

COMMENT ON TABLE "MST_STAFF" IS '스태프 마스터';
COMMENT ON COLUMN "MST_STAFF"."DESC" IS '설명';
COMMENT ON COLUMN "MST_STAFF"."STATUS" IS '사용유무 (Y/N)';
COMMENT ON COLUMN "MST_STAFF"."STAFF_ID" IS '스태프 ID';
COMMENT ON COLUMN "MST_STAFF"."NAME" IS '스태프명';
COMMENT ON COLUMN "MST_STAFF"."EMPLOYEE_NO" IS '사번';
COMMENT ON COLUMN "MST_STAFF"."DEPARTMENT" IS '부서';
COMMENT ON COLUMN "MST_STAFF"."DEPT_CODE" IS '부서코드';
COMMENT ON COLUMN "MST_STAFF"."RESPONS" IS '담당업무';
COMMENT ON COLUMN "MST_STAFF"."EMAIL" IS '이메일';
COMMENT ON COLUMN "MST_STAFF"."TEL" IS '연락처';
COMMENT ON COLUMN "MST_STAFF"."MPHONE" IS '휴대전화번호';

-- 공동작업 그룹 LIST (스태프 그룹 관리, 그룹별 스태프 행)
CREATE SEQUENCE "MST_COWORK_ID_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE "MST_COWORK" (
    "COWORK_ID"     NUMBER(20) NOT NULL,                    -- 공동작업그룹 ID (MST_COWORK_ID_SEQ.NEXTVAL 사용)
    "STAFF_ID"      NUMBER REFERENCES "MST_STAFF"("STAFF_ID"), -- 스태프 ID
    "COWORK_NAME"   VARCHAR2(200) NOT NULL,                 -- 그룹명
    "WORK_TYPE"     VARCHAR2(50),                            -- 작업유형
    "STATUS"        VARCHAR2(20) DEFAULT 'ACTIVE',          -- 상태 (ACTIVE/INACTIVE)
    "DESC"          VARCHAR2(2000),                         -- 설명
    "CREATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP,         -- 등록일시
    "UPDATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP,         -- 수정일시
    CONSTRAINT "PK_COWORK" PRIMARY KEY ("COWORK_ID", "STAFF_ID")
);

COMMENT ON TABLE "MST_COWORK" IS '공동작업 그룹 LIST (스태프 그룹 관리, 그룹별 스태프 행)';
COMMENT ON COLUMN "MST_COWORK"."COWORK_ID" IS '공동작업그룹 ID';
COMMENT ON COLUMN "MST_COWORK"."STAFF_ID" IS '스태프 ID (MST_STAFF)';
COMMENT ON COLUMN "MST_COWORK"."COWORK_NAME" IS '그룹명';
COMMENT ON COLUMN "MST_COWORK"."WORK_TYPE" IS '작업유형';
COMMENT ON COLUMN "MST_COWORK"."DESC" IS '설명';
COMMENT ON COLUMN "MST_COWORK"."STATUS" IS '상태 (ACTIVE/INACTIVE)';
COMMENT ON COLUMN "MST_COWORK"."CREATED_AT" IS '등록일시';
COMMENT ON COLUMN "MST_COWORK"."UPDATED_AT" IS '수정일시';



-- 서버 마스터 (Server)
CREATE TABLE "MST_SERVER" (
    "SERVER_ID"     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 서버 ID
    "SERVER_NAME"   VARCHAR2(200) NOT NULL,                 -- 서버명
    "STATUS"        VARCHAR2(20) DEFAULT 'ACTIVE',          -- 상태 (ACTIVE/INACTIVE 등)
    "HOSTNAME"      VARCHAR2(255),                         -- 호스트명
    "IP_ADDRESS"    VARCHAR2(45),                          -- IP 주소
    "OS_TYPE"       VARCHAR2(100),                         -- OS 유형
    "OS_VERSION"    VARCHAR2(100),                          -- OS 버전
    "CPU_CORES"     NUMBER(10),                             -- CPU 코어 수
    "CPU_MODEL"     VARCHAR2(200),                         -- CPU 모델명
    "MEMORY_GB"     NUMBER(10,2),                           -- 메모리(GB)
    "LOCATION"      VARCHAR2(200),                          -- 물리적 위치
    "SYS_STAGE"     VARCHAR2(20),                          -- 시스템 단계 (DEV/STG/PRD 등)
    "NW_ZONE"       VARCHAR2(100),                         -- 네트워크 존
    "VIP"           VARCHAR2(255),                         -- VIP
    "LB"            VARCHAR2(255),                         -- LB (로드밸런서)
    "COWORK_ID"     NUMBER REFERENCES "MST_COWORK"("COWORK_ID"), -- 담당 공동작업그룹 (MST_COWORK 그룹)
    "VEN_NAME"   VARCHAR2(200),                         -- 벤더명 (병합)
    "VEN_PHONE" VARCHAR2(50),                          -- 벤더 연락처
    "VEN_EMAIL" VARCHAR2(255),                         -- 벤더 이메일
    "VEN_ADDR"       VARCHAR2(500),                         -- 벤더 주소
    "VEN_SAL_NAME"   VARCHAR2(100),                      -- 영업대표 (1인)
    "VEN_SAL_PHONE"  VARCHAR2(50),                      -- 영업대표 전화번호
    "VEN_SAL_EMAIL"  VARCHAR2(255),                      -- 영업대표 이메일
    "VEN_STF1_NAME"   VARCHAR2(100),                      -- 담당자 1
    "VEN_STF1_PHONE"  VARCHAR2(50),                      -- 담당자 1 전화번호
    "VEN_STF1_EMAIL"  VARCHAR2(255),                     -- 담당자 1 이메일
    "VEN_STF2_NAME"   VARCHAR2(100),                      -- 담당자 2
    "VEN_STF2_PHONE"  VARCHAR2(50),                      -- 담당자 2 전화번호
    "VEN_STF2_EMAIL"  VARCHAR2(255),                     -- 담당자 2 이메일
    "DESC"          VARCHAR2(2000),                        -- 설명
    "CREATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP,         -- 등록일시
    "UPDATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP          -- 수정일시
);

COMMENT ON TABLE "MST_SERVER" IS '서버 마스터';
COMMENT ON COLUMN "MST_SERVER"."SERVER_ID" IS '서버 ID';
COMMENT ON COLUMN "MST_SERVER"."SERVER_NAME" IS '서버명';
COMMENT ON COLUMN "MST_SERVER"."HOSTNAME" IS '호스트명';
COMMENT ON COLUMN "MST_SERVER"."IP_ADDRESS" IS 'IP 주소';
COMMENT ON COLUMN "MST_SERVER"."OS_TYPE" IS 'OS 유형';
COMMENT ON COLUMN "MST_SERVER"."OS_VERSION" IS 'OS 버전';
COMMENT ON COLUMN "MST_SERVER"."CPU_CORES" IS 'CPU 코어 수';
COMMENT ON COLUMN "MST_SERVER"."CPU_MODEL" IS 'CPU 모델명';
COMMENT ON COLUMN "MST_SERVER"."MEMORY_GB" IS '메모리(GB)';
COMMENT ON COLUMN "MST_SERVER"."LOCATION" IS '물리적 위치';
COMMENT ON COLUMN "MST_SERVER"."DESC" IS '설명';
COMMENT ON COLUMN "MST_SERVER"."STATUS" IS '상태 (ACTIVE/INACTIVE 등)';
COMMENT ON COLUMN "MST_SERVER"."SYS_STAGE" IS '시스템 단계 (DEV/STG/PRD 등)';
COMMENT ON COLUMN "MST_SERVER"."NW_ZONE" IS '네트워크 존';
COMMENT ON COLUMN "MST_SERVER"."VIP" IS 'VIP';
COMMENT ON COLUMN "MST_SERVER"."LB" IS 'LB (로드밸런서)';
COMMENT ON COLUMN "MST_SERVER"."VEN_NAME" IS '벤더명';
COMMENT ON COLUMN "MST_SERVER"."VEN_PHONE" IS '벤더 연락처';
COMMENT ON COLUMN "MST_SERVER"."VEN_EMAIL" IS '벤더 이메일';
COMMENT ON COLUMN "MST_SERVER"."VEN_ADDR" IS '벤더 주소';
COMMENT ON COLUMN "MST_SERVER"."VEN_SAL_NAME" IS '영업대표 (1인)';
COMMENT ON COLUMN "MST_SERVER"."VEN_SAL_PHONE" IS '영업대표 전화번호';
COMMENT ON COLUMN "MST_SERVER"."VEN_SAL_EMAIL" IS '영업대표 이메일';
COMMENT ON COLUMN "MST_SERVER"."VEN_STF1_NAME" IS '담당자 1';
COMMENT ON COLUMN "MST_SERVER"."VEN_STF1_PHONE" IS '담당자 1 전화번호';
COMMENT ON COLUMN "MST_SERVER"."VEN_STF1_EMAIL" IS '담당자 1 이메일';
COMMENT ON COLUMN "MST_SERVER"."VEN_STF2_NAME" IS '담당자 2';
COMMENT ON COLUMN "MST_SERVER"."VEN_STF2_PHONE" IS '담당자 2 전화번호';
COMMENT ON COLUMN "MST_SERVER"."VEN_STF2_EMAIL" IS '담당자 2 이메일';
COMMENT ON COLUMN "MST_SERVER"."COWORK_ID" IS '담당 공동작업그룹 (MST_COWORK 그룹)';


-- 솔루션 마스터 (Solution) - 벤더 정보 병합
CREATE TABLE "MST_SOLU" (
    "SOLU_ID"   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 솔루션 ID
    "SOLU_NAME" VARCHAR2(200) NOT NULL,                 -- 솔루션명
    "STATUS"        VARCHAR2(20) DEFAULT 'ACTIVE',         -- 상태 (ACTIVE/INACTIVE 등)
    "VERSION"       VARCHAR2(50),                          -- 버전
    "PRG_LANG"      VARCHAR2(100),                         -- 개발언어 (Programming Language)
    "JAVA_YN"       CHAR(1),                               -- Java 사용 여부 (Y/N)
    "SOLU_TYPE" VARCHAR2(100),                         -- 솔루션 유형
    "ACCOUNT"  VARCHAR2(100),                         -- 계정명
    "PWD"           VARCHAR2(200),                         -- 비밀번호
    "PWD_EXPIRE_DT" DATE,                                    -- 비번만료일
    "COWORK_ID"     NUMBER REFERENCES "MST_COWORK"("COWORK_ID"), -- 담당 공동작업그룹 (MST_COWORK 그룹)
    "VEN_NAME"   VARCHAR2(200),                         -- 벤더명 (병합)
    "VEN_PHONE" VARCHAR2(50),                          -- 벤더 연락처
    "VEN_EMAIL" VARCHAR2(255),                         -- 벤더 이메일
    "VEN_ADDR"       VARCHAR2(500),                         -- 벤더 주소
    "VEN_SAL_NAME"  VARCHAR2(100),                        -- 영업대표 (1인)
    "VEN_SAL_PHONE" VARCHAR2(50),                         -- 영업대표 전화번호
    "VEN_SAL_EMAIL" VARCHAR2(255),                        -- 영업대표 이메일
    "VEN_STF1_NAME"  VARCHAR2(100),                        -- 스태프 1
    "VEN_STF1_PHONE" VARCHAR2(50),                        -- 스태프 1 전화번호
    "VEN_STF1_EMAIL" VARCHAR2(255),                        -- 스태프 1 이메일
    "VEN_STF2_NAME"  VARCHAR2(100),                        -- 스태프 2
    "VEN_STF2_PHONE" VARCHAR2(50),                        -- 스태프 2 전화번호
    "VEN_STF2_EMAIL" VARCHAR2(255),                        -- 스태프 2 이메일
    "VEN_DESC" VARCHAR2(2000),                              -- 벤더 설명
    "DESC"   VARCHAR2(2000),                        -- 설명
    "CREATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP,         -- 등록일시
    "UPDATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP         -- 수정일시
);

COMMENT ON TABLE "MST_SOLU" IS '솔루션 마스터 (벤더 정보 병합)';
COMMENT ON COLUMN "MST_SOLU"."SOLU_ID" IS '솔루션 ID';
COMMENT ON COLUMN "MST_SOLU"."SOLU_NAME" IS '솔루션명';
COMMENT ON COLUMN "MST_SOLU"."VERSION" IS '버전';
COMMENT ON COLUMN "MST_SOLU"."PRG_LANG" IS '개발언어 (Programming Language)';
COMMENT ON COLUMN "MST_SOLU"."JAVA_YN" IS 'Java 사용 여부 (Y/N)';
COMMENT ON COLUMN "MST_SOLU"."SOLU_TYPE" IS '솔루션 유형';
COMMENT ON COLUMN "MST_SOLU"."DESC" IS '설명';
COMMENT ON COLUMN "MST_SOLU"."VEN_NAME" IS '벤더명';
COMMENT ON COLUMN "MST_SOLU"."VEN_PHONE" IS '벤더 연락처';
COMMENT ON COLUMN "MST_SOLU"."VEN_EMAIL" IS '벤더 이메일';
COMMENT ON COLUMN "MST_SOLU"."VEN_ADDR" IS '벤더 주소';
COMMENT ON COLUMN "MST_SOLU"."VEN_SAL_NAME" IS '영업대표 (1인)';
COMMENT ON COLUMN "MST_SOLU"."VEN_SAL_PHONE" IS '영업대표 전화번호';
COMMENT ON COLUMN "MST_SOLU"."VEN_SAL_EMAIL" IS '영업대표 이메일';
COMMENT ON COLUMN "MST_SOLU"."VEN_STF1_NAME" IS '스태프 1';
COMMENT ON COLUMN "MST_SOLU"."VEN_STF1_PHONE" IS '스태프 1 전화번호';
COMMENT ON COLUMN "MST_SOLU"."VEN_STF1_EMAIL" IS '스태프 1 이메일';
COMMENT ON COLUMN "MST_SOLU"."VEN_STF2_NAME" IS '스태프 2';
COMMENT ON COLUMN "MST_SOLU"."VEN_STF2_PHONE" IS '스태프 2 전화번호';
COMMENT ON COLUMN "MST_SOLU"."VEN_STF2_EMAIL" IS '스태프 2 이메일';
COMMENT ON COLUMN "MST_SOLU"."VEN_DESC" IS '벤더 설명';
COMMENT ON COLUMN "MST_SOLU"."STATUS" IS '상태 (ACTIVE/INACTIVE 등)';
COMMENT ON COLUMN "MST_SOLU"."ACCOUNT" IS '계정명';
COMMENT ON COLUMN "MST_SOLU"."PWD" IS '비밀번호';
COMMENT ON COLUMN "MST_SOLU"."PWD_EXPIRE_DT" IS '비번만료일';
COMMENT ON COLUMN "MST_SOLU"."COWORK_ID" IS '담당 공동작업그룹 (MST_COWORK 그룹)';


-- 앱 마스터 (Application) - 벤더 정보 병합
CREATE TABLE "MST_APP" (
    "APP_ID"        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 앱 ID
    "APP_NAME"      VARCHAR2(200) NOT NULL,                 -- 앱명
    "STATUS"        VARCHAR2(20) DEFAULT 'ACTIVE',          -- 상태 (ACTIVE/INACTIVE 등)
    "VERSION"       VARCHAR2(50),                           -- 버전
    "PRG_LANG"      VARCHAR2(100),                         -- 개발언어 (Programming Language)
    "JAVA_YN"       CHAR(1),                                -- Java 사용 여부 (Y/N)
    "APP_TYPE"      VARCHAR2(100),                         -- 앱 유형
    "ACCOUNT"  VARCHAR2(100),                          -- 계정명
    "PWD"           VARCHAR2(200),                         -- 비밀번호
    "PWD_EXPIRE_DT" DATE,                                   -- 비번만료일
    "COWORK_ID"     NUMBER(20),                             -- 담당 공동작업그룹 (MST_COWORK 그룹)
    "DESC"          VARCHAR2(2000),                        -- 설명
    "CREATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP,         -- 등록일시
    "UPDATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP         -- 수정일시
);

COMMENT ON TABLE "MST_APP" IS '앱 마스터 (벤더 정보 병합)';
COMMENT ON COLUMN "MST_APP"."APP_ID" IS '앱 ID';
COMMENT ON COLUMN "MST_APP"."APP_NAME" IS '앱명';
COMMENT ON COLUMN "MST_APP"."VERSION" IS '버전';
COMMENT ON COLUMN "MST_APP"."PRG_LANG" IS '개발언어 (Programming Language)';
COMMENT ON COLUMN "MST_APP"."JAVA_YN" IS 'Java 사용 여부 (Y/N)';
COMMENT ON COLUMN "MST_APP"."APP_TYPE" IS '앱 유형';
COMMENT ON COLUMN "MST_APP"."DESC" IS '설명';
COMMENT ON COLUMN "MST_APP"."STATUS" IS '상태 (ACTIVE/INACTIVE 등)';
COMMENT ON COLUMN "MST_APP"."COWORK_ID" IS '담당 공동작업그룹 (MST_COWORK 그룹)';
COMMENT ON COLUMN "MST_APP"."ACCOUNT" IS '계정명';
COMMENT ON COLUMN "MST_APP"."PWD" IS '비밀번호';
COMMENT ON COLUMN "MST_APP"."PWD_EXPIRE_DT" IS '비번만료일';
COMMENT ON COLUMN "MST_APP"."CREATED_AT" IS '등록일시';
COMMENT ON COLUMN "MST_APP"."UPDATED_AT" IS '수정일시';


-- Docu 마스터 (문서/보고서 보관 - 패치·정기점검 작업 후 보고서 등)
CREATE TABLE "MST_DOCU" (
    "DOCU_ID"           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 문서 ID
    "TITLE"             VARCHAR2(300) NOT NULL,                 -- 문서 제목
    "STATUS"        VARCHAR2(20) DEFAULT 'ACTIVE',          -- 상태 (ACTIVE/INACTIVE 등)
    "DOC_TYPE"          VARCHAR2(50),                            -- 문서 유형 (PATCH_REPORT, INSPECTION_REPORT 등)
    "SOURCE_TYPE"       VARCHAR2(30),                            -- 출처 유형 (PATCH, INSPECTION)
    "SOURCE_ID"         NUMBER(10),                              -- 출처 ID (패치ID 또는 점검ID)
    "STORAGE_TYPE"      CHAR(1),                                 -- 저장 방식 (D=DB, F=파일서버)
    "FILE_CONTENT"      BLOB,                                    -- 파일 바이너리 (DB 저장 시, 작은 파일)
    "FILE_PATH"         VARCHAR2(500),                           -- 파일 경로/URL (파일서버 저장 시)
    "FILE_NAME"         VARCHAR2(255),                            -- 원본 파일명
    "FILE_SIZE"         NUMBER(15),                              -- 파일 크기(byte)
    "FILE_SUMMARY_JSON" VARCHAR2(2000),                                    -- 파일 요약정보 (JSON)
    "DESC"              VARCHAR2(2000),                         -- 설명
    "CREATED_BY"        NUMBER(10) REFERENCES "MST_STAFF"("STAFF_ID"),  -- 등록자
    "CREATED_AT"        TIMESTAMP DEFAULT SYSTIMESTAMP,         -- 등록일시
    "UPDATED_AT"        TIMESTAMP DEFAULT SYSTIMESTAMP          -- 수정일시
);

COMMENT ON TABLE "MST_DOCU" IS 'Docu 마스터 (패치·정기점검 작업 보고서 등 문서 보관)';
COMMENT ON COLUMN "MST_DOCU"."DOCU_ID" IS '문서 ID';
COMMENT ON COLUMN "MST_DOCU"."TITLE" IS '문서 제목';
COMMENT ON COLUMN "MST_DOCU"."DOC_TYPE" IS '문서 유형 (PATCH_REPORT, INSPECTION_REPORT 등)';
COMMENT ON COLUMN "MST_DOCU"."SOURCE_TYPE" IS '출처 유형 (PATCH, INSPECTION)';
COMMENT ON COLUMN "MST_DOCU"."SOURCE_ID" IS '출처 ID (패치ID 또는 점검ID)';
COMMENT ON COLUMN "MST_DOCU"."STORAGE_TYPE" IS '저장 방식 (D=DB, F=파일서버)';
COMMENT ON COLUMN "MST_DOCU"."FILE_CONTENT" IS '파일 바이너리 (DB 저장 시)';
COMMENT ON COLUMN "MST_DOCU"."FILE_PATH" IS '파일 경로/URL (파일서버 저장 시)';
COMMENT ON COLUMN "MST_DOCU"."FILE_NAME" IS '원본 파일명';
COMMENT ON COLUMN "MST_DOCU"."FILE_SIZE" IS '파일 크기(byte)';
COMMENT ON COLUMN "MST_DOCU"."FILE_SUMMARY_JSON" IS '파일 요약정보 (JSON)';
COMMENT ON COLUMN "MST_DOCU"."DESC" IS '설명';
COMMENT ON COLUMN "MST_DOCU"."CREATED_BY" IS '등록자';
COMMENT ON COLUMN "MST_DOCU"."CREATED_AT" IS '등록일시';
COMMENT ON COLUMN "MST_DOCU"."UPDATED_AT" IS '수정일시';

