-- ============================================================
-- ICT 운영관리 - 관계 테이블
-- 서버-솔루션 N:M, 서버/솔루션별 담당자 2명, 벤더 2명
-- ============================================================

-- 서버별 설치 솔루션 (서버 1 : 솔루션 N)
CREATE TABLE "SERVER_SOLUTION" (
    "SERVER_SOLUTION_ID" SERIAL PRIMARY KEY,               -- PK
    "SERVER_ID"          INTEGER NOT NULL REFERENCES "SERVER_MASTER"("SERVER_ID") ON DELETE CASCADE,  -- 서버 ID
    "SOLUTION_ID"        INTEGER NOT NULL REFERENCES "SOLUTION_MASTER"("SOLUTION_ID") ON DELETE CASCADE,  -- 솔루션 ID
    "INSTALLED_VERSION"  VARCHAR(50),                     -- 설치된 버전
    "INSTALLED_AT"       DATE,                            -- 설치일
    "NOTES"              TEXT,                            -- 비고
    "CREATED_AT"         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 등록일시
    UNIQUE ("SERVER_ID", "SOLUTION_ID")
);

COMMENT ON TABLE "SERVER_SOLUTION" IS '서버별 설치 솔루션 (한 서버에 여러 솔루션 설치)';
COMMENT ON COLUMN "SERVER_SOLUTION"."SERVER_SOLUTION_ID" IS 'PK';
COMMENT ON COLUMN "SERVER_SOLUTION"."SERVER_ID" IS '서버 ID';
COMMENT ON COLUMN "SERVER_SOLUTION"."SOLUTION_ID" IS '솔루션 ID';
COMMENT ON COLUMN "SERVER_SOLUTION"."INSTALLED_VERSION" IS '설치된 버전';
COMMENT ON COLUMN "SERVER_SOLUTION"."INSTALLED_AT" IS '설치일';
COMMENT ON COLUMN "SERVER_SOLUTION"."NOTES" IS '비고';


-- 서버 담당자 (서버당 담당자 2명, position 1=1차, 2=2차)
CREATE TABLE "SERVER_STAFF" (
    "SERVER_STAFF_ID" SERIAL PRIMARY KEY,                 -- PK
    "SERVER_ID"       INTEGER NOT NULL REFERENCES "SERVER_MASTER"("SERVER_ID") ON DELETE CASCADE,  -- 서버 ID
    "STAFF_ID"        INTEGER NOT NULL REFERENCES "STAFF_MASTER"("STAFF_ID") ON DELETE CASCADE,  -- 담당자 ID
    "POSITION"        SMALLINT NOT NULL CHECK ("POSITION" IN (1, 2)),  -- 1=1차 담당자, 2=2차 담당자
    "CREATED_AT"      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 등록일시
    UNIQUE ("SERVER_ID", "POSITION")
);

COMMENT ON TABLE "SERVER_STAFF" IS '서버 담당자 (1차/2차 각 1명)';
COMMENT ON COLUMN "SERVER_STAFF"."POSITION" IS '1=1차 담당자, 2=2차 담당자';


-- 서버 벤더 (서버당 벤더 2곳, position 1=1차, 2=2차)
CREATE TABLE "SERVER_VENDOR" (
    "SERVER_VENDOR_ID" SERIAL PRIMARY KEY,                -- PK
    "SERVER_ID"        INTEGER NOT NULL REFERENCES "SERVER_MASTER"("SERVER_ID") ON DELETE CASCADE,  -- 서버 ID
    "VENDOR_ID"        INTEGER NOT NULL REFERENCES "VENDOR_MASTER"("VENDOR_ID") ON DELETE CASCADE,  -- 벤더 ID
    "POSITION"         SMALLINT NOT NULL CHECK ("POSITION" IN (1, 2)),  -- 1=1차 벤더, 2=2차 벤더
    "CONTRACT_TYPE"    VARCHAR(100),                      -- 계약 유형
    "CREATED_AT"       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 등록일시
    UNIQUE ("SERVER_ID", "POSITION")
);

COMMENT ON TABLE "SERVER_VENDOR" IS '서버 벤더 (1차/2차 각 1곳)';
COMMENT ON COLUMN "SERVER_VENDOR"."POSITION" IS '1=1차 벤더, 2=2차 벤더';


-- 솔루션 담당자 (솔루션당 담당자 2명)
CREATE TABLE "SOLUTION_STAFF" (
    "SOLUTION_STAFF_ID" SERIAL PRIMARY KEY,                -- PK
    "SOLUTION_ID"       INTEGER NOT NULL REFERENCES "SOLUTION_MASTER"("SOLUTION_ID") ON DELETE CASCADE,  -- 솔루션 ID
    "STAFF_ID"          INTEGER NOT NULL REFERENCES "STAFF_MASTER"("STAFF_ID") ON DELETE CASCADE,  -- 담당자 ID
    "POSITION"          SMALLINT NOT NULL CHECK ("POSITION" IN (1, 2)),  -- 1=1차 담당자, 2=2차 담당자
    "CREATED_AT"        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 등록일시
    UNIQUE ("SOLUTION_ID", "POSITION")
);

COMMENT ON TABLE "SOLUTION_STAFF" IS '솔루션 담당자 (1차/2차 각 1명)';


-- 솔루션 벤더 (솔루션당 벤더 2곳)
CREATE TABLE "SOLUTION_VENDOR" (
    "SOLUTION_VENDOR_ID" SERIAL PRIMARY KEY,               -- PK
    "SOLUTION_ID"        INTEGER NOT NULL REFERENCES "SOLUTION_MASTER"("SOLUTION_ID") ON DELETE CASCADE,  -- 솔루션 ID
    "VENDOR_ID"          INTEGER NOT NULL REFERENCES "VENDOR_MASTER"("VENDOR_ID") ON DELETE CASCADE,  -- 벤더 ID
    "POSITION"           SMALLINT NOT NULL CHECK ("POSITION" IN (1, 2)),  -- 1=1차 벤더, 2=2차 벤더
    "CONTRACT_TYPE"      VARCHAR(100),                    -- 계약 유형
    "CREATED_AT"         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 등록일시
    UNIQUE ("SOLUTION_ID", "POSITION")
);

COMMENT ON TABLE "SOLUTION_VENDOR" IS '솔루션 벤더 (1차/2차 각 1곳)';
