-- ============================================================
-- ICT 운영관리 - 업무 정보 테이블
-- 패치관리업무, 정기점검업무
-- ============================================================

-- 패치관리업무 정보 (서버/솔루션 패치 작업 관리)
-- SERVER_ID만 있으면 서버(OS 등) 패치, SOLUTION_ID만 있으면 솔루션 패치,
-- 둘 다 있으면 해당 서버에 설치된 해당 솔루션 패치
CREATE TABLE "PATCH_MANAGEMENT" (
    "PATCH_ID"        SERIAL PRIMARY KEY,                 -- 패치 작업 ID
    "SERVER_ID"       INTEGER REFERENCES "SERVER_MASTER"("SERVER_ID") ON DELETE SET NULL,  -- 대상 서버
    "SOLUTION_ID"     INTEGER REFERENCES "SOLUTION_MASTER"("SOLUTION_ID") ON DELETE SET NULL,  -- 대상 솔루션
    "TITLE"           VARCHAR(300) NOT NULL,              -- 작업 제목
    "PATCH_TYPE"      VARCHAR(50),                        -- 패치 유형 (OS/보안/앱 등)
    "DESCRIPTION"     TEXT,                               -- 설명
    "PLANNED_DATE"    DATE,                               -- 계획일
    "COMPLETED_DATE"  DATE,                               -- 완료일
    "STATUS"          VARCHAR(30) DEFAULT 'PLANNED',     -- 상태 (PLANNED/IN_PROGRESS/COMPLETED/CANCELLED 등)
    "RESULT_NOTES"    TEXT,                               -- 작업 결과 메모
    "CREATED_BY"      INTEGER REFERENCES "STAFF_MASTER"("STAFF_ID"),  -- 등록자
    "CREATED_AT"      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 등록일시
    "UPDATED_AT"      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 수정일시
    CONSTRAINT CHK_PATCH_TARGET CHECK (
        "SERVER_ID" IS NOT NULL OR "SOLUTION_ID" IS NOT NULL
    )
);

COMMENT ON TABLE "PATCH_MANAGEMENT" IS '패치관리업무 정보 (서버/솔루션 패치 작업)';
COMMENT ON COLUMN "PATCH_MANAGEMENT"."PATCH_ID" IS '패치 작업 ID';
COMMENT ON COLUMN "PATCH_MANAGEMENT"."SERVER_ID" IS '대상 서버 (NULL이면 솔루션 전체 패치)';
COMMENT ON COLUMN "PATCH_MANAGEMENT"."SOLUTION_ID" IS '대상 솔루션 (NULL이면 서버만 패치)';
COMMENT ON COLUMN "PATCH_MANAGEMENT"."TITLE" IS '작업 제목';
COMMENT ON COLUMN "PATCH_MANAGEMENT"."PATCH_TYPE" IS '패치 유형 (OS/보안/앱 등)';
COMMENT ON COLUMN "PATCH_MANAGEMENT"."PLANNED_DATE" IS '계획일';
COMMENT ON COLUMN "PATCH_MANAGEMENT"."COMPLETED_DATE" IS '완료일';
COMMENT ON COLUMN "PATCH_MANAGEMENT"."STATUS" IS '상태 (PLANNED/IN_PROGRESS/COMPLETED/CANCELLED 등)';
COMMENT ON COLUMN "PATCH_MANAGEMENT"."RESULT_NOTES" IS '작업 결과 메모';


-- 정기점검업무 정보 (벤더 방문 점검 관리)
CREATE TABLE "REGULAR_INSPECTION" (
    "INSPECTION_ID"   SERIAL PRIMARY KEY,                 -- 점검 ID
    "VENDOR_ID"       INTEGER NOT NULL REFERENCES "VENDOR_MASTER"("VENDOR_ID") ON DELETE CASCADE,  -- 방문 벤더
    "SERVER_ID"       INTEGER REFERENCES "SERVER_MASTER"("SERVER_ID") ON DELETE SET NULL,  -- 점검 대상 서버
    "SOLUTION_ID"     INTEGER REFERENCES "SOLUTION_MASTER"("SOLUTION_ID") ON DELETE SET NULL,  -- 점검 대상 솔루션
    "TITLE"           VARCHAR(300) NOT NULL,              -- 점검 제목
    "SCHEDULED_DATE"  DATE NOT NULL,                      -- 예정일
    "ACTUAL_DATE"     DATE,                               -- 실제 방문일
    "INSPECTION_TYPE" VARCHAR(50),                        -- 점검 유형
    "RESULT"          VARCHAR(30),                        -- 점검 결과 (PASS/FAIL/PARTIAL 등)
    "FINDINGS"        TEXT,                               -- 점검 소견
    "ACTION_ITEMS"    TEXT,                               -- 조치 사항
    "CREATED_AT"      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 등록일시
    "UPDATED_AT"      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 수정일시
    CONSTRAINT CHK_INSPECTION_TARGET CHECK (
        "SERVER_ID" IS NOT NULL OR "SOLUTION_ID" IS NOT NULL
    )
);

COMMENT ON TABLE "REGULAR_INSPECTION" IS '정기점검업무 정보 (벤더 방문 점검)';
COMMENT ON COLUMN "REGULAR_INSPECTION"."INSPECTION_ID" IS '점검 ID';
COMMENT ON COLUMN "REGULAR_INSPECTION"."VENDOR_ID" IS '방문 벤더';
COMMENT ON COLUMN "REGULAR_INSPECTION"."SERVER_ID" IS '점검 대상 서버';
COMMENT ON COLUMN "REGULAR_INSPECTION"."SOLUTION_ID" IS '점검 대상 솔루션';
COMMENT ON COLUMN "REGULAR_INSPECTION"."TITLE" IS '점검 제목';
COMMENT ON COLUMN "REGULAR_INSPECTION"."SCHEDULED_DATE" IS '예정일';
COMMENT ON COLUMN "REGULAR_INSPECTION"."ACTUAL_DATE" IS '실제 방문일';
COMMENT ON COLUMN "REGULAR_INSPECTION"."INSPECTION_TYPE" IS '점검 유형';
COMMENT ON COLUMN "REGULAR_INSPECTION"."RESULT" IS '점검 결과 (PASS/FAIL/PARTIAL 등)';
COMMENT ON COLUMN "REGULAR_INSPECTION"."FINDINGS" IS '점검 소견';
COMMENT ON COLUMN "REGULAR_INSPECTION"."ACTION_ITEMS" IS '조치 사항';


-- 업무 테이블 조회용 인덱스
CREATE INDEX "IDX_PATCH_MANAGEMENT_SERVER" ON "PATCH_MANAGEMENT"("SERVER_ID");
CREATE INDEX "IDX_PATCH_MANAGEMENT_SOLUTION" ON "PATCH_MANAGEMENT"("SOLUTION_ID");
CREATE INDEX "IDX_PATCH_MANAGEMENT_PLANNED" ON "PATCH_MANAGEMENT"("PLANNED_DATE");
CREATE INDEX "IDX_PATCH_MANAGEMENT_STATUS" ON "PATCH_MANAGEMENT"("STATUS");

CREATE INDEX "IDX_REGULAR_INSPECTION_VENDOR" ON "REGULAR_INSPECTION"("VENDOR_ID");
CREATE INDEX "IDX_REGULAR_INSPECTION_SCHEDULED" ON "REGULAR_INSPECTION"("SCHEDULED_DATE");
CREATE INDEX "IDX_REGULAR_INSPECTION_SERVER" ON "REGULAR_INSPECTION"("SERVER_ID");
CREATE INDEX "IDX_REGULAR_INSPECTION_SOLUTION" ON "REGULAR_INSPECTION"("SOLUTION_ID");
