-- ============================================================
-- ICT 운영관리 - 업무 정보 테이블
-- 패치관리업무, 정기점검업무
-- ============================================================

-- 패치관리업무 정보 (서버/솔루션 패치 작업 관리)
CREATE TABLE "BZ_PATCH_MANAGEMENT" (
    "PATCH_ID"        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 패치 작업 ID
    "SERVER_ID"       NUMBER(10),                                            -- 대상 서버
    "SOLU_ID"         NUMBER(10),                                            -- 대상 솔루션
    "TITLE"           VARCHAR2(300) NOT NULL,                                -- 작업 제목
    "PATCH_TYPE"      VARCHAR2(50),                                         -- 패치 유형 (OS/보안/앱 등)
    "DESC"            VARCHAR2(2000),                                        -- 설명
    "PLANNED_DATE"    DATE,                                                  -- 계획일
    "COMPLETED_DATE"  DATE,                                                  -- 완료일
    "STATUS"          VARCHAR2(30) DEFAULT 'PLANNED',                        -- 상태
    "RESULT_NOTES"    VARCHAR2(4000),                                        -- 작업 결과 메모
    "DOCU_ID"         NUMBER(10),                                            -- 연결 문서 (작업 보고서 등)
    "CREATED_BY"      NUMBER(10),                                            -- 등록자
    "CREATED_AT"      TIMESTAMP DEFAULT SYSTIMESTAMP,                       -- 등록일시
    "UPDATED_AT"      TIMESTAMP DEFAULT SYSTIMESTAMP,                      -- 수정일시
    CONSTRAINT "CHK_PATCH_TARGET" CHECK ("SERVER_ID" IS NOT NULL OR "SOLU_ID" IS NOT NULL),
    CONSTRAINT "FK_PM_SERVER" FOREIGN KEY ("SERVER_ID") REFERENCES "MST_SERVER"("SERVER_ID") ON DELETE SET NULL,
    CONSTRAINT "FK_PM_SOLU" FOREIGN KEY ("SOLU_ID") REFERENCES "MST_SOLU"("SOLU_ID") ON DELETE SET NULL,
    CONSTRAINT "FK_PM_DOCU" FOREIGN KEY ("DOCU_ID") REFERENCES "MST_DOCU"("DOCU_ID") ON DELETE SET NULL,
    CONSTRAINT "FK_PM_CREATED_BY" FOREIGN KEY ("CREATED_BY") REFERENCES "MST_STAFF"("STAFF_ID")
);

COMMENT ON TABLE "BZ_PATCH_MANAGEMENT" IS '패치관리업무 정보 (서버/솔루션 패치 작업)';
COMMENT ON COLUMN "BZ_PATCH_MANAGEMENT"."PATCH_ID" IS '패치 작업 ID';
COMMENT ON COLUMN "BZ_PATCH_MANAGEMENT"."SERVER_ID" IS '대상 서버 (NULL이면 솔루션 전체 패치)';
COMMENT ON COLUMN "BZ_PATCH_MANAGEMENT"."SOLU_ID" IS '대상 솔루션 (NULL이면 서버만 패치)';
COMMENT ON COLUMN "BZ_PATCH_MANAGEMENT"."TITLE" IS '작업 제목';
COMMENT ON COLUMN "BZ_PATCH_MANAGEMENT"."PATCH_TYPE" IS '패치 유형 (OS/보안/앱 등)';
COMMENT ON COLUMN "BZ_PATCH_MANAGEMENT"."PLANNED_DATE" IS '계획일';
COMMENT ON COLUMN "BZ_PATCH_MANAGEMENT"."COMPLETED_DATE" IS '완료일';
COMMENT ON COLUMN "BZ_PATCH_MANAGEMENT"."STATUS" IS '상태 (PLANNED/IN_PROGRESS/COMPLETED/CANCELLED 등)';
COMMENT ON COLUMN "BZ_PATCH_MANAGEMENT"."RESULT_NOTES" IS '작업 결과 메모';
COMMENT ON COLUMN "BZ_PATCH_MANAGEMENT"."DOCU_ID" IS '연결 문서 (작업 보고서 등, MST_DOCU)';


-- 정기점검업무 정보 (벤더 방문 점검 관리)
CREATE TABLE "BZ_REGULAR_INSPECTION" (
    "INSPECTION_ID"   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 점검 ID
    "VENDOR_NAME"     VARCHAR2(200),                                        -- 방문 벤더명
    "SERVER_ID"       NUMBER(10),                                           -- 점검 대상 서버
    "SOLU_ID"         NUMBER(10),                                           -- 점검 대상 솔루션
    "TITLE"           VARCHAR2(300) NOT NULL,                               -- 점검 제목
    "SCHEDULED_DATE"  DATE NOT NULL,                                       -- 예정일
    "ACTUAL_DATE"     DATE,                                                 -- 실제 방문일
    "INSPECTION_TYPE" VARCHAR2(50),                                         -- 점검 유형
    "RESULT"          VARCHAR2(30),                                         -- 점검 결과 (PASS/FAIL/PARTIAL 등)
    "FINDINGS"        VARCHAR2(4000),                                      -- 점검 소견
    "ACTION_ITEMS"    VARCHAR2(4000),                                      -- 조치 사항
    "DOCU_ID"         NUMBER(10),                                           -- 연결 문서 (점검 보고서 등)
    "CREATED_AT"      TIMESTAMP DEFAULT SYSTIMESTAMP,                       -- 등록일시
    "UPDATED_AT"      TIMESTAMP DEFAULT SYSTIMESTAMP,                      -- 수정일시
    CONSTRAINT "CHK_INSPECTION_TARGET" CHECK ("SERVER_ID" IS NOT NULL OR "SOLU_ID" IS NOT NULL),
    CONSTRAINT "FK_RI_SERVER" FOREIGN KEY ("SERVER_ID") REFERENCES "MST_SERVER"("SERVER_ID") ON DELETE SET NULL,
    CONSTRAINT "FK_RI_SOLU" FOREIGN KEY ("SOLU_ID") REFERENCES "MST_SOLU"("SOLU_ID") ON DELETE SET NULL,
    CONSTRAINT "FK_RI_DOCU" FOREIGN KEY ("DOCU_ID") REFERENCES "MST_DOCU"("DOCU_ID") ON DELETE SET NULL
);

COMMENT ON TABLE "BZ_REGULAR_INSPECTION" IS '정기점검업무 정보 (벤더 방문 점검)';
COMMENT ON COLUMN "BZ_REGULAR_INSPECTION"."INSPECTION_ID" IS '점검 ID';
COMMENT ON COLUMN "BZ_REGULAR_INSPECTION"."VENDOR_NAME" IS '방문 벤더명';
COMMENT ON COLUMN "BZ_REGULAR_INSPECTION"."SERVER_ID" IS '점검 대상 서버';
COMMENT ON COLUMN "BZ_REGULAR_INSPECTION"."SOLU_ID" IS '점검 대상 솔루션';
COMMENT ON COLUMN "BZ_REGULAR_INSPECTION"."TITLE" IS '점검 제목';
COMMENT ON COLUMN "BZ_REGULAR_INSPECTION"."SCHEDULED_DATE" IS '예정일';
COMMENT ON COLUMN "BZ_REGULAR_INSPECTION"."ACTUAL_DATE" IS '실제 방문일';
COMMENT ON COLUMN "BZ_REGULAR_INSPECTION"."INSPECTION_TYPE" IS '점검 유형';
COMMENT ON COLUMN "BZ_REGULAR_INSPECTION"."RESULT" IS '점검 결과 (PASS/FAIL/PARTIAL 등)';
COMMENT ON COLUMN "BZ_REGULAR_INSPECTION"."FINDINGS" IS '점검 소견';
COMMENT ON COLUMN "BZ_REGULAR_INSPECTION"."ACTION_ITEMS" IS '조치 사항';
COMMENT ON COLUMN "BZ_REGULAR_INSPECTION"."DOCU_ID" IS '연결 문서 (점검 보고서 등, MST_DOCU)';


-- 업무 테이블 조회용 인덱스
CREATE INDEX "IDX_BZ_PATCH_MANAGEMENT_SERVER" ON "BZ_PATCH_MANAGEMENT"("SERVER_ID");
CREATE INDEX "IDX_BZ_PATCH_MANAGEMENT_SOLU" ON "BZ_PATCH_MANAGEMENT"("SOLU_ID");
CREATE INDEX "IDX_BZ_PATCH_MANAGEMENT_PLANNED" ON "BZ_PATCH_MANAGEMENT"("PLANNED_DATE");
CREATE INDEX "IDX_BZ_PATCH_MANAGEMENT_STATUS" ON "BZ_PATCH_MANAGEMENT"("STATUS");
CREATE INDEX "IDX_BZ_PATCH_MANAGEMENT_DOCU" ON "BZ_PATCH_MANAGEMENT"("DOCU_ID");

CREATE INDEX "IDX_BZ_REGULAR_INSPECTION_VENDOR" ON "BZ_REGULAR_INSPECTION"("VENDOR_NAME");
CREATE INDEX "IDX_BZ_REGULAR_INSPECTION_SCHEDULED" ON "BZ_REGULAR_INSPECTION"("SCHEDULED_DATE");
CREATE INDEX "IDX_BZ_REGULAR_INSPECTION_SERVER" ON "BZ_REGULAR_INSPECTION"("SERVER_ID");
CREATE INDEX "IDX_BZ_REGULAR_INSPECTION_SOLU" ON "BZ_REGULAR_INSPECTION"("SOLU_ID");
CREATE INDEX "IDX_BZ_REGULAR_INSPECTION_DOCU" ON "BZ_REGULAR_INSPECTION"("DOCU_ID");



-- TODO LIST (할일 관리)
CREATE TABLE "BZ_TODO_LIST" (
    "TODO_ID"       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 할일 ID
    "TITLE"         VARCHAR2(300) NOT NULL,                                -- 제목
    "DESC"          VARCHAR2(2000),                                        -- 설명
    "STATUS"        VARCHAR2(30) DEFAULT 'OPEN',                            -- 상태 (OPEN/IN_PROGRESS/DONE/CANCELLED)
    "PRIORITY"      VARCHAR2(20),                                          -- 우선순위 (HIGH/MEDIUM/LOW)
    "DUE_DATE"      DATE,                                                   -- 마감일
    "ASSIGNED_TO"   NUMBER,                                                -- 담당자
    "CREATED_BY"    NUMBER(10),                                             -- 등록자
    "CREATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP,                         -- 등록일시
    "UPDATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP,                         -- 수정일시
    "COMPLETED_AT"  TIMESTAMP,                                              -- 완료일시
    CONSTRAINT "FK_TODO_ASSIGNED" FOREIGN KEY ("ASSIGNED_TO") REFERENCES "MST_COWORK"("COWORK_ID") ON DELETE SET NULL,
    CONSTRAINT "FK_TODO_CREATED_BY" FOREIGN KEY ("CREATED_BY") REFERENCES "MST_STAFF"("STAFF_ID")
);

COMMENT ON TABLE "BZ_TODO_LIST" IS 'TODO LIST (할일 관리)';
COMMENT ON COLUMN "BZ_TODO_LIST"."TODO_ID" IS '할일 ID';
COMMENT ON COLUMN "BZ_TODO_LIST"."TITLE" IS '제목';
COMMENT ON COLUMN "BZ_TODO_LIST"."DESC" IS '설명';
COMMENT ON COLUMN "BZ_TODO_LIST"."STATUS" IS '상태 (OPEN/IN_PROGRESS/DONE/CANCELLED)';
COMMENT ON COLUMN "BZ_TODO_LIST"."PRIORITY" IS '우선순위 (HIGH/MEDIUM/LOW)';
COMMENT ON COLUMN "BZ_TODO_LIST"."DUE_DATE" IS '마감일';
COMMENT ON COLUMN "BZ_TODO_LIST"."ASSIGNED_TO" IS '담당자';
COMMENT ON COLUMN "BZ_TODO_LIST"."CREATED_BY" IS '등록자';
COMMENT ON COLUMN "BZ_TODO_LIST"."CREATED_AT" IS '등록일시';
COMMENT ON COLUMN "BZ_TODO_LIST"."UPDATED_AT" IS '수정일시';
COMMENT ON COLUMN "BZ_TODO_LIST"."COMPLETED_AT" IS '완료일시';


-- TODO_ACT LIST (TODO 서브 작업)
CREATE TABLE "BZ_TODO_ACT_LIST" (
    "TODO_ACT_ID"     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 서브작업 ID
    "TODO_ID"         NUMBER NOT NULL,                                      -- 상위 할일 (BZ_TODO_LIST.TODO_ID와 동일 타입)
    "TITLE"           VARCHAR2(300) NOT NULL,                                -- 제목
    "DESC"            VARCHAR2(2000),                                        -- 설명
    "STATUS"          VARCHAR2(30) DEFAULT 'OPEN',                           -- 상태 (OPEN/IN_PROGRESS/DONE/CANCELLED)
    "PRIORITY"        VARCHAR2(20),                                          -- 우선순위 (HIGH/MEDIUM/LOW)
    "DUE_DATE"        DATE,                                                  -- 마감일
    "ASSIGNED_TO"     NUMBER,                                                -- 담당자
    "DISPLAY_ORDER"   NUMBER(5) DEFAULT 0,                                  -- 표시 순서
    "CREATED_AT"      TIMESTAMP DEFAULT SYSTIMESTAMP,                       -- 등록일시
    "UPDATED_AT"      TIMESTAMP DEFAULT SYSTIMESTAMP,                       -- 수정일시
    "COMPLETED_AT"    TIMESTAMP,                                            -- 완료일시
    CONSTRAINT "FK_TODO_ACT_TODO" FOREIGN KEY ("TODO_ID") REFERENCES "BZ_TODO_LIST"("TODO_ID") ON DELETE CASCADE,
    CONSTRAINT "FK_TODO_ACT_ASSIGNED" FOREIGN KEY ("ASSIGNED_TO") REFERENCES "MST_COWORK"("COWORK_ID") ON DELETE SET NULL
);

COMMENT ON TABLE "BZ_TODO_ACT_LIST" IS 'TODO_ACT LIT (TODO 서브 작업)';
COMMENT ON COLUMN "BZ_TODO_ACT_LIST"."TODO_ACT_ID" IS '서브작업 ID';
COMMENT ON COLUMN "BZ_TODO_ACT_LIST"."TODO_ID" IS '상위 할일 (BZ_TODO_LIST)';
COMMENT ON COLUMN "BZ_TODO_ACT_LIST"."TITLE" IS '제목';
COMMENT ON COLUMN "BZ_TODO_ACT_LIST"."DESC" IS '설명';
COMMENT ON COLUMN "BZ_TODO_ACT_LIST"."STATUS" IS '상태 (OPEN/IN_PROGRESS/DONE/CANCELLED)';
COMMENT ON COLUMN "BZ_TODO_ACT_LIST"."PRIORITY" IS '우선순위 (HIGH/MEDIUM/LOW)';
COMMENT ON COLUMN "BZ_TODO_ACT_LIST"."DUE_DATE" IS '마감일';
COMMENT ON COLUMN "BZ_TODO_ACT_LIST"."ASSIGNED_TO" IS '담당자';
COMMENT ON COLUMN "BZ_TODO_ACT_LIST"."DISPLAY_ORDER" IS '표시 순서';
COMMENT ON COLUMN "BZ_TODO_ACT_LIST"."CREATED_AT" IS '등록일시';
COMMENT ON COLUMN "BZ_TODO_ACT_LIST"."UPDATED_AT" IS '수정일시';
COMMENT ON COLUMN "BZ_TODO_ACT_LIST"."COMPLETED_AT" IS '완료일시';

